### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by LucasDoCouto** [LucasDoCouto/URL-shortening-API#1]
TODO LIST:
- [x] Mobile Version
- [x] Mobile Menu
- [ ] Mobile Font Styles improvement
- [ ] Mobile Background improvement
- [ ] Desktop Version
- [ ] Desktop Menu
- [x] API Integration
- [ ] Copy to Clipboard Button
- [ ] Duplicated URL Check
- [ ] URL validation
